### ISSUE TITLE
[QUICK ISSUE] Capstone ERD scope

### ISSUE THREAD

**Issue by blusanders** [nss-day-cohort-46/How-to-Ask-for-Help#132]
#### REQUIRED Question or issue:
>>

I feel like I'm building my ERD for what my app could be rather than what realistically it should be. Specifically, I'm adding a step that creates a new join table (and adds complexity) that in a the real world would make sense, but for the sake of building an app that demonstrates my learning to this point seems like too much. Do I pull it back?  - Blu

#### REQUIRED Check all that apply:
- [ ] Rubber Ducking 
- [x] Direction/Guidance
- [ ] Check In (Pep talk, vent session, etc.)

#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICKS
```

**Comment by blusanders** [comment]
After typing this out I think I'm going to pull it back but would appreciate comments so I will leave open for now.

**Comment by Scott47** [comment]
@blusanders @ajawashington will review this with you in your 1:1. I would think about what you want your app to do and build an ERD for it. If it needs to be revised for any reason, we will help you with that. Your final proposal is still a proposal and first draft of your plan. If you want to link to your current ERD in your proposal or post a link to it here, I am happy to take a quick look. Otherwise, I suggest building the ERD as you think it should be built and have questions ready for your mentor. Remember, we will be meeting with people on a 'first come, first serve' basis. Completing the proposal gets the planning conversation started sooner :)

**Comment by blusanders** [comment]
https://dbdiagram.io/d/602e99d480d742080a3b1922

Thank you. I'm building a Per Diem app for a music tour. That's the goal. Literally a dollar amount and a bill breakdown. In the real world a crew member can be on multiple tours for multiple artists in any given year. Then they will be on multiple "runs" (a weekend of shows for example) on those tours. Adding the ability to be on multiple tours is correct in my real world brain, but doesn't really serve the app ultimately and makes it unnecessarily complicated. I'm realizing this as I respond and think through it. 

I'll add the other join table in the ERD and discuss why it makes sense but doesn't make practical sense for the app with Aja in the 1 on 1.

**Comment by Scott47** [comment]
Yeah. Looking at your ERD as it is, I think you have hit the nail on the head. That is something you can add as stretch.
